using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace DGVisionStudio.Infrastructure.Data;

public static class PricingDataSeeder
{
    private static readonly PricingSeed[] DefaultPricingItems =
    {
        new("Портретна фотография", "Индивидуални, артистични и професионални портретни фотосесии.", "Fixed", "От 60 € / фотосесия", 1),
        new("Абитуриентска фотография", "Сесии за абитуриенти с акцент върху стил, присъствие и детайл.", "Fixed", "От 60 € / час", 2),
        new("Заснемане на кръщене", "Дискретно и емоционално заснемане на важни семейни моменти.", "Fixed", "От 60 € / час", 3),
        new("Сватбена фотография", "Заснемане на сватбен ден, ключови моменти и атмосфера.", "Fixed", "120 € / час + 30 € дрон", 4),
        new("Продуктова фотография", "Кадри за продукти, брандове и онлайн магазини.", "Negotiable", null, 5),
        new("Рекламна фотография", "Съдържание за кампании, социални мрежи и бранд присъствие.", "Negotiable", null, 6),
        new("Корпоративна фотография", "Професионални кадри за екипи, бизнес среда и услуги.", "Negotiable", null, 7),
        new("Семейна фотография", "Естествени и емоционални кадри за семейства и деца.", "Negotiable", null, 8),
        new("Заснемане на събития", "Заснемане на частни, фирмени и сценични събития.", "Fixed", "От 60 € / час", 9)
    };

    public static async Task SeedAsync(IServiceProvider services)
    {
        using var scope = services.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<AppDbContext>();
        await EnsureTableAsync(db);
        await SeedAsync(db);
    }

    public static async Task EnsureTableAsync(AppDbContext db)
    {
        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "PricingItems" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "Title" character varying(150) NOT NULL,
                "Description" character varying(1200) NOT NULL,
                "PricingMode" character varying(40) NOT NULL,
                "PriceText" character varying(150) NULL,
                "DisplayOrder" integer NOT NULL,
                "IsActive" boolean NOT NULL DEFAULT TRUE,
                "CreatedAtUtc" timestamp with time zone NOT NULL DEFAULT NOW()
            );

            CREATE INDEX IF NOT EXISTS "IX_PricingItems_DisplayOrder" ON "PricingItems" ("DisplayOrder");
            CREATE INDEX IF NOT EXISTS "IX_PricingItems_IsActive" ON "PricingItems" ("IsActive");
            CREATE INDEX IF NOT EXISTS "IX_PricingItems_PricingMode" ON "PricingItems" ("PricingMode");
            """);
    }

    private static async Task SeedAsync(AppDbContext db)
    {
        var existingCount = await CountAsync(db);
        if (existingCount > 0) return;

        foreach (var item in DefaultPricingItems)
        {
            await db.Database.ExecuteSqlInterpolatedAsync($"""
                INSERT INTO "PricingItems" ("Title", "Description", "PricingMode", "PriceText", "DisplayOrder", "IsActive", "CreatedAtUtc")
                VALUES ({item.Title}, {item.Description}, {item.PricingMode}, {item.PriceText}, {item.DisplayOrder}, TRUE, NOW())
                """);
        }
    }

    private static async Task<int> CountAsync(AppDbContext db)
    {
        await using var command = db.Database.GetDbConnection().CreateCommand();
        command.CommandText = "SELECT COUNT(*) FROM \"PricingItems\"";

        if (command.Connection?.State != System.Data.ConnectionState.Open)
        {
            await db.Database.OpenConnectionAsync();
        }

        var result = await command.ExecuteScalarAsync();
        return Convert.ToInt32(result);
    }

    private sealed record PricingSeed(
        string Title,
        string Description,
        string PricingMode,
        string? PriceText,
        int DisplayOrder
    );
}
